export const actions = {  
  AGENTLOGIN: {verb: "AGENTLOGIN"},
  AGENTLOGOFF: {verb: "AGENTLOGOFF"},
  ADDMEMBER: {verb: "ADDMEMBER"},
  REMOVEMEMBER: {verb: "REMOVEMEMBER"},
  PAUSE: {verb: "PAUSEALL"},
  UNPAUSE: {verb: "UNPAUSEALL"},
  ENTERQUEUE: {verb: "ENTERQUEUE"},
  CONNECT: {verb: "CONNECT"},
  COMPLETEAGENT: {verb: "COMPLETEAGENT"},
  COMPLETECALLER: {verb: "COMPLETECALLER"},
}
